name: 'Find-and-replace strings'
description: 'A GitHub Action that performs find and replace operations on strings.'
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  source:
    description: 'The source string to perform find and replace on'
    required: true
  find:
    description: 'The text to search for within the source string'
    required: true
  replace:
    description: 'The text to replace found occurrences with'
    required: true
  replaceAll:
    description: 'Replace all occurrences (true) or just the first one (false, default)'
    required: false
outputs:
  value:
    description: 'The resulting string after find and replace operation'
runs:
  using: 'node20'
  main: 'dist/index.js'
